import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { generateQuestion } from './mathUtils';

export const generateWorksheetPDF = (config, numQuestions) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(22);
  doc.setTextColor(30, 41, 59); // slate-800
  doc.text("KidMaths Practice Worksheet", 105, 20, { align: "center" });
  
  // Subtitle / Config Info
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139); // slate-500
  const operationName = config.operation.charAt(0).toUpperCase() + config.operation.slice(1);
  doc.text(`Operation: ${operationName} | Mode: ${config.numberMode} | Questions: ${numQuestions}`, 105, 28, { align: "center" });

  // Name and Date lines
  doc.setFontSize(12);
  doc.text("Name: _______________________", 20, 40);
  doc.text("Date: _______________", 140, 40);

  // Generate Questions
  const questions = [];
  for (let i = 0; i < numQuestions; i++) {
    const q = generateQuestion(config.operation, config.difficulty, config.numberMode, config.customRange);
    questions.push(`${i + 1})   ${q.questionText} = _____`);
  }

  // We want to lay them out in 2 columns
  const body = [];
  for (let i = 0; i < questions.length; i += 2) {
    const col1 = questions[i] ? questions[i] : '';
    const col2 = questions[i + 1] ? questions[i + 1] : '';
    body.push([col1, col2]);
  }

  autoTable(doc, {
    startY: 50,
    head: [],
    body: body,
    theme: 'plain',
    styles: {
      fontSize: 16,
      cellPadding: 8,
      textColor: [30, 41, 59], // slate-800
    },
    columnStyles: {
      0: { cellWidth: '50%' },
      1: { cellWidth: '50%' },
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by KidMaths App`, 105, 285, { align: 'center' });
  }

  // Save the PDF
  doc.save(`kidmaths_worksheet_${operationName.toLowerCase()}.pdf`);
};
